RDKAAMP-3830: Unit tests fail to link on Ubuntu due to missing dl link
Reason for change: Fix link error on Ubuntu 20.04
We get undefined reference to dlsym

Risks: Low
Test Procedure: ./run.sh in tests/utests
Priority: P1

Change-Id: I62348f83c8a8d2d2f73fcd39b5c8b90052b1f333
Signed-off-by: gavin.parry2@sky.uk