XIONE-12304: [SKYXIONE][FLEX2][realtek]:  23Q2_sprint builds are failing ( error: 'AampCCManager' has not been declared) Reason for change: To fix compilation errors on Flex2 realtek builds Test Procedure: Successful compilation of AAMP Risks: Low
Signed-off-by: Amritha Suja Mohan <Amritha_SujaMohan@comcast.com>
Change-Id: Ib3d7756275d49e4d96ee1c2b765a668c7361d837
(cherry picked from commit b3f94998033db60efeee3ae4ddcdad897ed1a614)